---


- name: Create myregistry directory and sub-directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ regsfile }}/{{ regone  }}"
    - "{{ regsfile }}/{{ regone  }}/auth"
    - "{{ regsfile }}/{{ regone  }}/certs"
    - "{{ regsfile }}/{{ regone  }}/data"
    - "{{ regsfile }}/{{ regone  }}/data/registry"
    - "{{ regsfile }}/{{ regone  }}/downloads"
    - "{{ regsfile }}/{{ regone  }}/downloads/images"
    - "{{ regsfile }}/{{ regone  }}/downloads/tools"
    - "{{ regsfile }}/{{ regone  }}/downloads/secrets"


- name: Add myregistry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{ regone  }}'
    insertbefore: BOF
  become: yes

- name:  Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}_key.pem"
    
  
- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}.csr"
    privatekey_path: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}_key.pem"
    common_name: "{{ regone  }}.localdomain"

- name: Generate a Self Signed OpenSSL certificate for {{ regone  }}
  openssl_certificate:
    path: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}_crt.crt"
    privatekey_path: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}_key.pem"
    csr_path: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}.csr"
    provider: selfsigned

- name: Copy registry crt file to anchors
  copy:
    src: "{{ regsfile }}/{{ regone  }}/certs/{{ regone  }}_crt.crt"
    dest: /etc/pki/ca-trust/source/anchors/

- name: update-ca-trust
  command: update-ca-trust extract


- name: Generate htpasswd file for start-repository.sh
  command: htpasswd -bBc {{ regsfile }}/{{ regone  }}/auth/htpasswd admin redhat
  become: true

- name: Create a registry container
  containers.podman.podman_container:
    name: "{{ regone  }}"
    image: docker.io/library/registry:2
    state: started
    ports:
      - 5000:5000
    volume:
      - "{{ regsfile }}/{{ regone  }}/data:/var/lib/registry:z"
      - "{{ regsfile }}/{{ regone  }}/auth:/auth:z"
      - "{{ regsfile }}/{{ regone  }}/certs:/certs:z"
    env:
        REGISTRY_AUTH: "htpasswd"
        REGISTRY_AUTH_HTPASSWD_REALM: "Registry"
        REGISTRY_HTTP_SECRET: "ALongRandomSecretForRegistry"
        REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
        REGISTRY_HTTP_TLS_CERTIFICATE: /certs/{{ regone  }}_crt.crt
        REGISTRY_HTTP_TLS_KEY: /certs/{{ regone  }}_key.pem

